ci(package.json/semantic-release): try semantic-release/commit-analyzer instead of @bubbletechonogly
{ TypeError: cb is not a function

BREAKING CHANGE: at process._tickCallback (internal/process/next_tick.js:188:7)
pluginName:'@bubltechnology/customizable-commit-analyzer' }npm ERR! code ELIFECYCLE